import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/*
 * Two sidebars, because there are two readers.
 *
 * `help` is for somebody with the app open who wants to finish a task, so it is
 * ordered the way the app is used — get in, make a group, put money in it, get
 * it back out — rather than the way the app is built.
 *
 * `api` is generated: the reference pages under docs/api/reference are written
 * by docusaurus-plugin-openapi-docs from the OpenAPI document at build time, so
 * they are picked up by directory rather than listed by hand. A list would
 * drift the first time an endpoint is added.
 */
const sidebars: SidebarsConfig = {
  help: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/what-waves-is',
        'getting-started/create-your-account',
        'getting-started/your-first-group',
      ],
    },
    {
      type: 'category',
      label: 'Using Waves',
      collapsed: false,
      items: [
        'using-waves/add-an-expense',
        'using-waves/how-splitting-works',
        'using-waves/people-and-placeholders',
        'using-waves/balances',
        'using-waves/settle-up',
        'using-waves/receipts',
        'using-waves/personal-ledger',
      ],
    },
    {
      type: 'category',
      label: 'Privacy and your data',
      collapsed: false,
      items: [
        'privacy/discovery-settings',
        'privacy/export-your-data',
        'privacy/delete-your-account',
      ],
    },
  ],

  api: [
    'api/overview',
    'api/authentication',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      link: { type: 'doc', id: 'api/reference-intro' },
      items: [{ type: 'autogenerated', dirName: 'api/reference' }],
    },
  ],
};

export default sidebars;
