/**
 * iOS home-screen widget target — the Apple half of the widgets feature.
 *
 * Three launcher widgets (compact "Add expense", the search-style category
 * widget, and the action grid) live in this one WidgetKit extension, vended
 * together from the WidgetBundle in index.swift. They hold no data and share no
 * App Group: each region is a pure shortcut that opens the app at a deep link
 * (`waves:///…`) the app already routes. The Android sibling is generated by
 * plugins/withWavesWidgets.js.
 *
 * @type {import('@bacons/apple-targets/app.plugin').Config}
 */
module.exports = {
  type: 'widget',
  name: 'WavesWidgets',
  // Brand purple (`color.brand` in packages/ui). These $-prefixed keys feed the
  // target's Info.plist (WidgetBackground / accent); the SwiftUI views paint
  // their own literals of the theme colours (index.swift's Palette), since
  // Color("$…") can't read them.
  colors: {
    $accent: '#6C4EE3',
    $widgetBackground: '#FFFFFF',
  },
};
