/**
 * Drop `android:statusBarColor` / `android:navigationBarColor` from `AppTheme`.
 *
 * Expo's template writes both (as transparent) into `res/values/styles.xml`.
 * With `edgeToEdgeEnabled=true` and targetSdk 35+, Android draws the system bars
 * edge to edge and ignores these attributes, and Play Console's Android 15
 * check lists them as "deprecated APIs or parameters for edge-to-edge". The
 * bars are made transparent in code by React Native's own window setup, so the
 * attributes only add a warning.
 *
 * `android/` is generated by prebuild, so this is re-applied on every prebuild.
 */

const { withAndroidStyles } = require('expo/config-plugins');

const DEPRECATED = new Set(['android:statusBarColor', 'android:navigationBarColor']);

/** Style objects in, same objects out, minus the two deprecated items. */
function stripDeprecatedBarColors(styles) {
  for (const style of styles.resources?.style ?? []) {
    if (style.$?.name !== 'AppTheme' || !style.item) continue;
    style.item = style.item.filter((item) => !DEPRECATED.has(item.$?.name));
  }
  return styles;
}

module.exports = function withEdgeToEdgeTheme(config) {
  return withAndroidStyles(config, (c) => {
    c.modResults = stripDeprecatedBarColors(c.modResults);
    return c;
  });
};

module.exports.stripDeprecatedBarColors = stripDeprecatedBarColors;
