/**
 * Sign the release build with a real upload key — when one is configured.
 *
 * Expo's generated `build.gradle` ships this, with the warning still attached:
 *
 *     release {
 *         // Caution! In production, you need to generate your own keystore file.
 *         signingConfig signingConfigs.debug
 *     }
 *
 * A debug-signed build is fine to sideload and is rejected outright by Play. It
 * is also worse than it looks: the debug keystore is checked into every React
 * Native project on earth, so "signed" there means nothing at all.
 *
 * `android/` is generated by prebuild and is not tracked, so fixing this by hand
 * lasts exactly until the next `expo prebuild`. This plugin re-applies it every
 * time.
 *
 * WHERE THE KEY LIVES. Four Gradle properties, read from
 * `~/.gradle/gradle.properties` (or passed with `-P`), never from this
 * repository:
 *
 *     WAVES_UPLOAD_STORE_FILE=C:/keys/waves-upload.jks
 *     WAVES_UPLOAD_STORE_PASSWORD=…
 *     WAVES_UPLOAD_KEY_ALIAS=upload
 *     WAVES_UPLOAD_KEY_PASSWORD=…
 *
 * A path outside the project on purpose. A keystore inside the working tree is
 * one `git add -A` away from being published, and a signing key in a public
 * repository has to be treated as burned — which, if Play App Signing is not
 * enrolled, means the app can never be updated again.
 *
 * WHY IT FALLS BACK RATHER THAN FAILING. With no properties set, the release
 * build keeps the debug signing config and prints a line saying so. Anybody
 * cloning this repo — and every `assembleRelease` run to hand somebody a test
 * APK — keeps working without holding the production key. The build that
 * matters is the one that goes to Play, and that one is checked: `bundleRelease`
 * refuses to run debug-signed, because an AAB that Play rejects after a
 * ten-minute upload is a worse outcome than a build that stops in a second and
 * says why.
 */

const { withAppBuildGradle } = require('expo/config-plugins');

const MARKER = 'waves:release-signing';

/** The block Expo generates, and the anchor everything below is placed against. */
const DEBUG_SIGNING_CONFIG = `    signingConfigs {
        debug {`;

/**
 * Where the two values are declared: at project scope, above `android { }`.
 *
 * `def` inside `android { }` would be a local of that closure, invisible to the
 * task-graph guard at the foot of the file — which is a `Could not get unknown
 * property 'wavesHasUploadKey'` at configuration time, before any task runs.
 * `ext.` puts them on the project, where both readers can see them.
 */
const PROJECT_ANCHOR = 'android {';

const PROJECT_PROPERTIES = `// ${MARKER} — see apps/mobile/plugins/withReleaseSigning.js
// The upload key, read from ~/.gradle/gradle.properties. Absent, the release
// build falls back to debug signing: sideloadable, and refused by Play.
// On the project rather than in a closure: the guard at the foot of this file
// reads them too.
ext.wavesUploadStore = findProperty('WAVES_UPLOAD_STORE_FILE')
ext.wavesHasUploadKey = ext.wavesUploadStore != null && file(ext.wavesUploadStore).exists()

android {`;

const RELEASE_BUILD_TYPE = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;

const RELEASE_BUILD_TYPE_PATCHED = `        release {
            // ${MARKER} — see apps/mobile/plugins/withReleaseSigning.js
            signingConfig wavesHasUploadKey ? signingConfigs.release : signingConfigs.debug`;

/**
 * Declared after the debug config rather than inside the same brace, so the
 * `debug { … }` block Expo writes is left exactly as it is — this plugin has to
 * survive Expo rewording it.
 */
const UPLOAD_SIGNING_BLOCK = `        // ${MARKER}
        release {
            if (wavesHasUploadKey) {
                storeFile file(project.wavesUploadStore)
                storePassword findProperty('WAVES_UPLOAD_STORE_PASSWORD')
                keyAlias findProperty('WAVES_UPLOAD_KEY_ALIAS')
                keyPassword findProperty('WAVES_UPLOAD_KEY_PASSWORD')
            }
        }
`;

/**
 * The guard. A bundle is the Play artefact and nothing else, so a debug-signed
 * one is always a mistake; an APK is how this project hands somebody a build to
 * try, so it is only warned about.
 */
const BUNDLE_GUARD = `
// ${MARKER} — an AAB exists to be uploaded to Play, and Play rejects a
// debug-signed upload. Fail here, in a second, rather than after the upload.
gradle.taskGraph.whenReady { graph ->
    if (!wavesHasUploadKey && graph.allTasks.any { it.name.startsWith('bundleRelease') }) {
        throw new GradleException(
            'No upload key: set WAVES_UPLOAD_STORE_FILE, WAVES_UPLOAD_STORE_PASSWORD, ' +
            'WAVES_UPLOAD_KEY_ALIAS and WAVES_UPLOAD_KEY_PASSWORD in ~/.gradle/gradle.properties. ' +
            'See docs/play-release.md. (assembleRelease still works, debug-signed, for sideloading.)'
        )
    }
    if (!wavesHasUploadKey && graph.allTasks.any { it.name.startsWith('assembleRelease') }) {
        logger.lifecycle('waves: no upload key configured — release APK is DEBUG-SIGNED. Sideload only.')
    }
}
`;

/**
 * The whole edit, as a string in and a string out.
 *
 * Separated from the plugin so it can be tested against the real generated
 * `build.gradle` without standing up an Expo config pipeline — and it has to be
 * tested, because every anchor below is a quotation of Expo's template. When a
 * template changes, this must fail loudly at prebuild rather than quietly leave
 * the release build debug-signed, and a test is what proves it still would.
 *
 * Idempotent: applied twice, the second call is a no-op.
 */
function patchBuildGradle(contents) {
  if (contents.includes(MARKER)) return contents;

  // Every anchor is asserted rather than silently skipped. A miss means Expo
  // changed the template, and the failure this plugin exists to prevent is
  // precisely the silent one — a build that looks signed and is not.
  if (!contents.includes(DEBUG_SIGNING_CONFIG)) {
    throw new Error('withReleaseSigning: could not find signingConfigs in build.gradle');
  }
  if (!contents.includes(PROJECT_ANCHOR)) {
    throw new Error('withReleaseSigning: could not find the android block in build.gradle');
  }
  if (!contents.includes(RELEASE_BUILD_TYPE)) {
    throw new Error('withReleaseSigning: could not find the release buildType in build.gradle');
  }

  let next = contents.replace(PROJECT_ANCHOR, PROJECT_PROPERTIES);
  next = next.replace(RELEASE_BUILD_TYPE, RELEASE_BUILD_TYPE_PATCHED);

  // The upload config goes after the debug one closes. `signingConfigs` holds
  // only `debug` at this point, so the first `}` at that indent ends it.
  const DEBUG_CLOSE = '\n        }\n';
  const debugAt = next.indexOf('        debug {\n            storeFile');
  const debugEnds = debugAt === -1 ? -1 : next.indexOf(DEBUG_CLOSE, debugAt);
  if (debugEnds === -1) {
    throw new Error('withReleaseSigning: could not find the end of the debug signing config');
  }
  const after = debugEnds + DEBUG_CLOSE.length;
  next = `${next.slice(0, after)}${UPLOAD_SIGNING_BLOCK}${next.slice(after)}`;

  return `${next}\n${BUNDLE_GUARD}`;
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (gradleConfig) => {
    gradleConfig.modResults.contents = patchBuildGradle(gradleConfig.modResults.contents);
    return gradleConfig;
  });
};

module.exports.patchBuildGradle = patchBuildGradle;
