/**
 * The launch draws the mark from its first frame.
 *
 * Before this, Android's own splash was a bare purple field for as long as the
 * JS took to load, and only then did `AnimatedSplash` draw the mark on: a flat
 * violet screen, a pause, then a logo. It read as slow, not as a launch.
 *
 * Android 12's splash screen API takes an animated vector drawable as its icon
 * and plays it the instant the process starts, before any JS exists. So the
 * native half now draws the wave itself (the stroke inking along its path, the
 * dot landing) and `AnimatedSplash` picks up from the finished mark with the
 * swell and the lift. One gesture across both halves.
 *
 * The drawable is generated here, at prebuild, from `assets/brand/wave-mark.json`,
 * the same numbers `WaveMark` draws from, so the native mark and the JS mark
 * cannot drift apart. It is sized so the 512-unit canvas spans `MARK_WIDTH` dp
 * inside the 288dp splash icon, which is what `AnimatedSplash` draws at, and
 * centred the same way.
 *
 * Below Android 12 the compat library shows the drawable's first frame, which
 * is an undrawn mark on the field: the old bare launch, and `AnimatedSplash`
 * draws the whole mark as before.
 *
 * It has a name of its own, and the theme is pointed at it. `expo-splash-screen`
 * rewrites that theme too, so this plugin is listed BEFORE it in app.json:
 * config mods run in reverse order of registration, which makes this write the
 * last one. `splashNativeMark.test.ts` pins the order.
 */

const fs = require('node:fs');
const path = require('node:path');

const { withAndroidStyles, withDangerousMod } = require('expo/config-plugins');

const GEOM = require('../assets/brand/wave-mark.json');

const SPLASH_STYLE = 'Theme.App.SplashScreen';
const ICON_ATTR = 'windowSplashScreenAnimatedIcon';
const DURATION_ATTR = 'windowSplashScreenAnimationDuration';
/** Its own name: expo-splash-screen writes `splashscreen_logo` PNGs into every
    density folder, and a density-specific file would win over this one. */
const LOGO = 'splash_mark_animated';

/** The mark's drawn width in `AnimatedSplash` (its `MARK_WIDTH`). */
const MARK_WIDTH_DP = 140;
/** Android 12's splash icon box for an icon without a background. */
const ICON_DP = 288;

/** Timings, ms. The whole native gesture fits well inside the 1000ms the API allows. */
const DRAW_MS = 460;
const DOT_MS = 140;
/** How far above its resting place the dot starts, in canvas units (WaveMark's DOT_RISE). */
const DOT_RISE = 110;

/** WaveMark's `place`: geometry units to canvas units (scale, translate, lean, recentre). */
function place([x, y]) {
  const d = GEOM.derived;
  const c = GEOM.canvas;
  const t = (-GEOM.tiltDeg * Math.PI) / 180;
  const sx = x * d.scale + d.translate[0];
  const sy = y * d.scale + d.translate[1];
  const dx = sx - c / 2;
  const dy = sy - c / 2;
  return [
    c / 2 + dx * Math.cos(t) - dy * Math.sin(t) + d.recentre[0],
    c / 2 + dx * Math.sin(t) + dy * Math.cos(t) + d.recentre[1],
  ];
}

const fmt = (n) => Number(n.toFixed(3)).toString();

/** The stroke in canvas units. A quadratic stays a quadratic under an affine map. */
function strokePath() {
  const p = GEOM.points.map(place);
  return (
    `M${fmt(p[0][0])},${fmt(p[0][1])} ` +
    `Q${fmt(p[1][0])},${fmt(p[1][1])} ${fmt(p[2][0])},${fmt(p[2][1])} ` +
    `Q${fmt(p[3][0])},${fmt(p[3][1])} ${fmt(p[4][0])},${fmt(p[4][1])} ` +
    `Q${fmt(p[5][0])},${fmt(p[5][1])} ${fmt(p[6][0])},${fmt(p[6][1])}`
  );
}

/** The dot as a closed circle path, in canvas units. */
function dotPath() {
  const [cx, cy] = place([GEOM.dot.cx, GEOM.dot.cy]);
  const r = GEOM.dot.r * GEOM.derived.scale;
  return (
    `M${fmt(cx - r)},${fmt(cy)} ` +
    `a${fmt(r)},${fmt(r)} 0 1,0 ${fmt(2 * r)},0 ` +
    `a${fmt(r)},${fmt(r)} 0 1,0 ${fmt(-2 * r)},0 Z`
  );
}

/** The animated vector drawable, as text. Exported for the test. */
function animatedMarkXml() {
  const viewport = (GEOM.canvas * ICON_DP) / MARK_WIDTH_DP;
  const offset = (viewport - GEOM.canvas) / 2;
  const stroke = GEOM.strokeWidth * GEOM.derived.scale;
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAnimatedSplashMark.js from assets/brand/wave-mark.json.
     Do not hand-edit: android/ is regenerated on every prebuild. -->
<animated-vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt">
  <aapt:attr name="android:drawable">
    <vector
        android:width="${ICON_DP}dp"
        android:height="${ICON_DP}dp"
        android:viewportWidth="${fmt(viewport)}"
        android:viewportHeight="${fmt(viewport)}">
      <group android:translateX="${fmt(offset)}" android:translateY="${fmt(offset)}">
        <path
            android:name="stroke"
            android:pathData="${strokePath()}"
            android:strokeColor="#FFFFFF"
            android:strokeWidth="${fmt(stroke)}"
            android:strokeLineCap="round"
            android:strokeLineJoin="round"
            android:trimPathEnd="0" />
        <group android:name="dotFall" android:translateY="${-DOT_RISE}">
          <path
              android:name="dot"
              android:pathData="${dotPath()}"
              android:fillColor="#FFFFFF"
              android:fillAlpha="0" />
        </group>
      </group>
    </vector>
  </aapt:attr>
  <target android:name="stroke">
    <aapt:attr name="android:animation">
      <objectAnimator
          android:propertyName="trimPathEnd"
          android:valueFrom="0"
          android:valueTo="1"
          android:duration="${DRAW_MS}"
          android:interpolator="@android:interpolator/fast_out_slow_in" />
    </aapt:attr>
  </target>
  <target android:name="dot">
    <aapt:attr name="android:animation">
      <objectAnimator
          android:propertyName="fillAlpha"
          android:valueFrom="0"
          android:valueTo="1"
          android:startOffset="${DRAW_MS}"
          android:duration="1" />
    </aapt:attr>
  </target>
  <target android:name="dotFall">
    <aapt:attr name="android:animation">
      <objectAnimator
          android:propertyName="translateY"
          android:valueFrom="${-DOT_RISE}"
          android:valueTo="0"
          android:startOffset="${DRAW_MS}"
          android:duration="${DOT_MS}"
          android:interpolator="@android:interpolator/accelerate_quad" />
    </aapt:attr>
  </target>
</animated-vector>
`;
}

function withAnimatedMarkDrawable(config) {
  return withDangerousMod(config, [
    'android',
    (cfg) => {
      const drawables = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'drawable',
      );
      fs.mkdirSync(drawables, { recursive: true });
      fs.writeFileSync(path.join(drawables, `${LOGO}.xml`), animatedMarkXml(), 'utf8');
      return cfg;
    },
  ]);
}

function setItem(style, name, value) {
  style.item = style.item ?? [];
  const existing = style.item.find((i) => i.$?.name === name);
  if (existing) existing._ = value;
  else style.item.push({ $: { name }, _: value });
}

module.exports = function withAnimatedSplashMark(config) {
  return withAnimatedMarkDrawable(
    withAndroidStyles(config, (cfg) => {
      const styles = cfg.modResults.resources?.style ?? [];
      const splash = styles.find((s) => s.$?.name === SPLASH_STYLE);
      if (!splash) return cfg;
      setItem(splash, ICON_ATTR, `@drawable/${LOGO}`);
      setItem(splash, DURATION_ATTR, String(DRAW_MS + DOT_MS));
      return cfg;
    }),
  );
};

module.exports.animatedMarkXml = animatedMarkXml;
module.exports.NATIVE_DRAW_MS = DRAW_MS + DOT_MS;
