/**
 * The phone app opts out of Android Auto Backup.
 *
 * `android/` is generated by `expo prebuild`, so the manifest's
 * `android:allowBackup` comes from `app.json`. Left at the Android default
 * (`true`), a Google-Drive backup could carry the app's local state off the
 * device. That state is a cache of the server: the mirror is sealed with a key
 * that lives in SecureStore, which is never backed up. A restore would bring
 * back data it cannot open next to a session it no longer holds, so the backup
 * adds risk and gives nothing back. This test fails if the flag is removed.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

const appJson = JSON.parse(readFileSync(join(__dirname, '..', 'app.json'), 'utf8')) as {
  expo: { android?: { allowBackup?: boolean } };
};

describe('android backup', () => {
  it('is switched off in the config prebuild writes the manifest from', () => {
    expect(appJson.expo.android?.allowBackup).toBe(false);
  });
});
