import { describe, expect, it } from 'vitest';
import * as XLSX from 'xlsx';

import {
  BalanceDir,
  buildGroupExportModel,
  isRtlLocale,
  type ExportMemberInput,
  type GroupExportInput,
} from '@/data/groupExport';
import { escapeHtml, renderGroupExportHtml, type GroupExportLabels } from '@/data/groupExportHtml';
import {
  buildGroupExportWorkbook,
  workbookToBase64,
  type GroupExportSheetLabels,
} from '@/data/groupExportXlsx';
import type { ExpenseRow, SettlementRow } from '@/data/types';

// --- Fixtures --------------------------------------------------------------

const MEMBERS: ExportMemberInput[] = [
  { id: 'm-asha', name: 'Asha', role: 'admin', isGhost: false },
  { id: 'm-bala', name: 'Bala', role: 'member', isGhost: false },
  { id: 'm-ghost', name: 'Chic', role: 'member', isGhost: true },
];

/** Build a minimal but complete expense row. */
function expense(
  id: string,
  overrides: {
    description?: string;
    category?: string | null;
    amount: string;
    currency?: string;
    date?: string;
    payer: string;
    shares: string[];
    deleted?: boolean;
  },
): ExpenseRow {
  const currency = overrides.currency ?? 'INR';
  const each = (BigInt(overrides.amount) / BigInt(overrides.shares.length)).toString();
  return {
    id,
    group_id: 'g-1',
    deleted_at: overrides.deleted ? '2026-08-20T00:00:00.000Z' : null,
    created_at: '2026-08-01T00:00:00.000Z',
    currentVersion: {
      id: `${id}-v1`,
      version_no: 1,
      description: overrides.description ?? '',
      category: overrides.category ?? null,
      category_meta: null,
      expense_date: overrides.date ?? '2026-08-08',
      currency,
      amount: overrides.amount,
      split_type: 'equal',
      split_params: { kind: 'equal' } as never,
      author_member_id: overrides.payer,
      notes: null,
      payment_method: null,
      receipt_share_url: null,
      location: null,
      created_at: '2026-08-01T00:00:00.000Z',
      payers: [{ member_id: overrides.payer, amount: overrides.amount }],
      shares: overrides.shares.map((member) => ({ member_id: member, amount: each })),
    },
  };
}

const SETTLEMENT: SettlementRow = {
  id: 's-1',
  group_id: 'g-1',
  from_member_id: 'm-bala',
  to_member_id: 'm-asha',
  currency: 'INR',
  amount: '60000',
  method: 'cash' as SettlementRow['method'],
  status: 'confirmed' as SettlementRow['status'],
  note: null,
  initiated_at: '2026-08-10T00:00:00.000Z',
  confirmed_at: '2026-08-10T00:00:00.000Z',
};

function makeInput(locale = 'en-IN'): GroupExportInput {
  return {
    group: { name: 'Goa Trip', coverEmoji: '🏖️', type: 'trip', currency: 'INR' },
    members: MEMBERS,
    expenses: [
      expense('e-1', {
        description: 'Dinner',
        category: 'food',
        amount: '120000',
        payer: 'm-asha',
        shares: ['m-asha', 'm-bala'],
      }),
      expense('e-2', {
        description: 'Cancelled cab',
        amount: '50000',
        payer: 'm-bala',
        shares: ['m-asha', 'm-bala'],
        deleted: true,
      }),
    ],
    settlements: [SETTLEMENT],
    balances: new Map<string, bigint>([
      ['m-asha', 60000n],
      ['m-bala', -60000n],
      ['m-ghost', 0n],
    ]),
    labels: {
      appName: 'Waves',
      groupType: 'Trip',
      categories: { food: 'Food & drink' },
      methods: { cash: 'Cash', upi: 'UPI', bank: 'Bank transfer', other: 'Other' },
      untitled: 'Untitled',
      roleAdmin: 'Admin',
      roleMember: 'Member',
      notJoined: 'Not joined yet',
      someone: 'Someone',
      owed: 'is owed',
      owes: 'owes',
      settled: 'settled up',
    },
    generatedOnIso: '2026-08-27T12:00:00.000Z',
    locale,
  };
}

const PDF_LABELS: GroupExportLabels = {
  documentTitle: 'Group statement',
  generatedOn: 'Generated on',
  totalSpent: 'Total spent',
  membersLabel: 'Members',
  expensesLabel: 'Expenses',
  settlementsLabel: 'Settlements',
  balancesTitle: 'Balances',
  membersTitle: 'Members',
  colDate: 'Date',
  colDescription: 'Description',
  colCategory: 'Category',
  colPaidBy: 'Paid by',
  colAmount: 'Amount',
  colParticipants: 'Split between',
  colFrom: 'From',
  colTo: 'To',
  colMethod: 'Method',
  colStatus: 'Status',
  colMember: 'Member',
  colRole: 'Role',
  colBalance: 'Balance',
  colDirection: 'Standing',
  noneYet: 'Nothing here yet',
  deletedTag: 'deleted',
  footer: 'Generated by Waves',
};

const SHEET_LABELS: GroupExportSheetLabels = {
  sheetSummary: 'Summary',
  sheetExpenses: 'Expenses',
  sheetSettlements: 'Settlements',
  sheetBalances: 'Balances',
  sheetMembers: 'Members',
  fieldGroup: 'Group',
  fieldType: 'Type',
  fieldCurrency: 'Currency',
  fieldGeneratedOn: 'Generated on',
  fieldMembers: 'Members',
  fieldExpenses: 'Expenses',
  fieldSettlements: 'Settlements',
  fieldTotalSpent: 'Total spent',
  colDate: 'Date',
  colDescription: 'Description',
  colCategory: 'Category',
  colPaidBy: 'Paid by',
  colParticipants: 'Split between',
  colAmount: 'Amount',
  colDisplay: 'Formatted',
  colCurrency: 'Currency',
  colDeleted: 'Deleted',
  colFrom: 'From',
  colTo: 'To',
  colMethod: 'Method',
  colStatus: 'Status',
  colCount: 'Count',
  colMember: 'Member',
  colRole: 'Role',
  colDirection: 'Standing',
  colBalance: 'Balance',
  colJoined: 'Joined',
  yes: 'Yes',
  no: 'No',
};

// --- Model -----------------------------------------------------------------

describe('buildGroupExportModel', () => {
  it('assembles group meta, counts and per-currency totals', () => {
    const model = buildGroupExportModel(makeInput());

    expect(model.groupName).toBe('Goa Trip');
    expect(model.coverEmoji).toBe('🏖️');
    expect(model.groupType).toBe('Trip');
    expect(model.currency).toBe('INR');
    expect(model.memberCount).toBe(3);
    // Deleted expenses stay in the list (append-only ledger)…
    expect(model.expenseCount).toBe(2);
    expect(model.settlementCount).toBe(1);

    // …but are excluded from the spend totals.
    expect(model.totals).toHaveLength(1);
    expect(model.totals[0].amount.currency).toBe('INR');
    expect(model.totals[0].amount.minor).toBe(120000n);
    expect(model.totals[0].amount.value).toBe(1200);
    expect(model.totals[0].count).toBe(1);
  });

  it('resolves names, categories, split participants and formats money', () => {
    const model = buildGroupExportModel(makeInput());
    const dinner = model.expenses.find((row) => row.id === 'e-1')!;

    expect(dinner.description).toBe('Dinner');
    expect(dinner.category).toBe('Food & drink');
    expect(dinner.paidBy).toBe('Asha');
    expect(dinner.participants).toBe('Asha, Bala');
    expect(dinner.participantCount).toBe(2);
    expect(dinner.deleted).toBe(false);
    // INR minor units → localized display + summable major value.
    expect(dinner.amount.value).toBe(1200);
    expect(dinner.amount.text).toContain('₹');
    expect(dinner.amount.text).toContain('1,200');

    const cab = model.expenses.find((row) => row.id === 'e-2')!;
    expect(cab.deleted).toBe(true);
  });

  it('derives balances with direction and a clean magnitude', () => {
    const model = buildGroupExportModel(makeInput());
    const asha = model.balances.find((row) => row.memberId === 'm-asha')!;
    const bala = model.balances.find((row) => row.memberId === 'm-bala')!;
    const ghost = model.balances.find((row) => row.memberId === 'm-ghost')!;

    expect(asha.direction).toBe(BalanceDir.Owed);
    expect(asha.directionText).toBe('is owed');
    expect(asha.signedValue).toBe(600);
    // The magnitude carries no minus — the direction word does that job.
    expect(asha.amount.text).not.toContain('-');
    expect(asha.amount.text).toContain('600');

    expect(bala.direction).toBe(BalanceDir.Owes);
    expect(bala.signedValue).toBe(-600);
    expect(bala.amount.text).not.toContain('-');

    expect(ghost.direction).toBe(BalanceDir.Settled);
    expect(ghost.directionText).toBe('settled up');
    expect(ghost.signedValue).toBe(0);
  });

  it('maps roles and localizes the settlement method', () => {
    const model = buildGroupExportModel(makeInput());
    expect(model.members[0].role).toBe('Admin');
    expect(model.members[1].role).toBe('Member');
    expect(model.members[2].isGhost).toBe(true);

    expect(model.settlements[0].from).toBe('Bala');
    expect(model.settlements[0].to).toBe('Asha');
    expect(model.settlements[0].method).toBe('Cash');
    expect(model.settlements[0].amount.value).toBe(600);
  });

  it('flags Arabic as RTL', () => {
    expect(isRtlLocale('ar')).toBe(true);
    expect(isRtlLocale('ar-EG')).toBe(true);
    expect(isRtlLocale('en-IN')).toBe(false);
    expect(buildGroupExportModel(makeInput('ar')).isRtl).toBe(true);
    expect(buildGroupExportModel(makeInput('en-IN')).isRtl).toBe(false);
  });
});

// --- HTML template ---------------------------------------------------------

describe('renderGroupExportHtml', () => {
  it('includes the header, summary and all three tables with money', () => {
    const html = renderGroupExportHtml(buildGroupExportModel(makeInput()), PDF_LABELS);

    expect(html).toContain('Goa Trip');
    expect(html).toContain('Waves');
    expect(html).toContain('Trip');
    // Summary band labels + counts.
    expect(html).toContain('Total spent');
    expect(html).toContain('Balances');
    // Table headers.
    expect(html).toContain('Paid by');
    expect(html).toContain('From');
    expect(html).toContain('Method');
    // Rows.
    expect(html).toContain('Dinner');
    expect(html).toContain('Asha');
    expect(html).toContain('is owed');
    // Money renders with symbol.
    expect(html).toContain('₹');
    // Deleted expense is kept and tagged, not dropped.
    expect(html).toContain('Cancelled cab');
    expect(html).toContain('deleted');
    // Footer.
    expect(html).toContain('Generated by Waves');
  });

  it('is LTR for English and RTL for Arabic', () => {
    const ltr = renderGroupExportHtml(buildGroupExportModel(makeInput('en-IN')), PDF_LABELS);
    expect(ltr).toContain('dir="ltr"');

    const rtl = renderGroupExportHtml(buildGroupExportModel(makeInput('ar')), PDF_LABELS);
    expect(rtl).toContain('dir="rtl"');
  });

  it('escapes HTML in dynamic text', () => {
    const input = makeInput();
    const withMarkup = {
      ...input,
      expenses: [
        expense('e-x', {
          description: '<script>alert(1)</script>',
          amount: '10000',
          payer: 'm-asha',
          shares: ['m-asha'],
        }),
      ],
    };
    const html = renderGroupExportHtml(buildGroupExportModel(withMarkup), PDF_LABELS);
    expect(html).toContain('&lt;script&gt;');
    expect(html).not.toContain('<script>alert(1)</script>');
  });

  it('escapeHtml handles the dangerous characters', () => {
    expect(escapeHtml('a & b < c > d "e" \'f\'')).toBe(
      'a &amp; b &lt; c &gt; d &quot;e&quot; &#39;f&#39;',
    );
  });
});

// --- Excel workbook --------------------------------------------------------

describe('buildGroupExportWorkbook', () => {
  it('builds the five expected sheets', () => {
    const wb = buildGroupExportWorkbook(buildGroupExportModel(makeInput()), SHEET_LABELS);
    expect(wb.SheetNames).toEqual(['Summary', 'Expenses', 'Settlements', 'Balances', 'Members']);
  });

  it('writes expense money as a numeric major value beside its currency', () => {
    const wb = buildGroupExportWorkbook(buildGroupExportModel(makeInput()), SHEET_LABELS);
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets.Expenses);
    const dinner = rows.find((row) => row.Description === 'Dinner')!;

    expect(dinner['Paid by']).toBe('Asha');
    expect(dinner.Amount).toBe(1200);
    expect(typeof dinner.Amount).toBe('number');
    expect(dinner.Currency).toBe('INR');
    expect(dinner.Deleted).toBe('No');
  });

  it('writes signed balances that sum to zero', () => {
    const wb = buildGroupExportWorkbook(buildGroupExportModel(makeInput()), SHEET_LABELS);
    const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets.Balances);
    const sum = rows.reduce((total, row) => total + (row.Balance as number), 0);
    expect(sum).toBe(0);
  });

  it('serialises to a base64 .xlsx (zip) payload', () => {
    const wb = buildGroupExportWorkbook(buildGroupExportModel(makeInput()), SHEET_LABELS);
    const base64 = workbookToBase64(wb);
    expect(typeof base64).toBe('string');
    expect(base64.length).toBeGreaterThan(0);
    // A .xlsx is a zip; its first bytes are "PK" → base64 begins "UEs".
    expect(base64.startsWith('UEs')).toBe(true);
  });
});

describe('edge rows', () => {
  it('renders an expense with no version as an empty, zero row in the group currency', () => {
    // Given an expense whose current version never arrived
    const bare = { ...expense('e-3', { amount: '0', payer: 'm-asha', shares: ['m-asha'] }) };
    bare.currentVersion = null as unknown as ExpenseRow['currentVersion'];
    const input: GroupExportInput = { ...makeInput(), expenses: [bare] };
    // When the model is built
    const row = buildGroupExportModel(input).expenses[0]!;
    // Then it carries no date, no payer, and a zero amount — and it is not totalled
    expect(row.dateText).toBe('');
    expect(row.paidBy).toBe('');
    expect(row.participantCount).toBe(0);
    expect(row.amount.minor).toBe(0n);
    expect(row.amount.currency).toBe('INR');
    expect(buildGroupExportModel(input).totals).toEqual([]);
  });

  it('keeps an unparseable date as written and names an unknown member "someone"', () => {
    const input: GroupExportInput = {
      ...makeInput(),
      expenses: [
        expense('e-4', { amount: '100', payer: 'm-stranger', shares: ['m-asha'], date: 'soon' }),
      ],
    };
    const row = buildGroupExportModel(input).expenses[0]!;
    expect(row.dateText).toBe('soon');
    expect(row.paidBy).toBe('Someone');
  });

  it('shows the "nothing here yet" row in every table when the group is empty', () => {
    const input: GroupExportInput = { ...makeInput(), members: [], expenses: [], settlements: [] };
    const html = renderGroupExportHtml(buildGroupExportModel(input), PDF_LABELS);
    // expenses, settlements, balances and members tables each get the placeholder
    expect(html.match(/class="empty"/g)?.length).toBe(4);
    expect(html).toContain('Nothing here yet');
  });
});
